<style>
BODY.codisto-categories-index #anchor-content
{
	width: 100%;
    padding: 0px;
    position: absolute;
    right: 0px;
    left: 88px;
    bottom: 0px;
    top: 92px;
}

BODY.codisto-categories-index #anchor-content #page\:main-container
{
    position: absolute;
    top: 0px;
    left: 0px;
    right: 0px;
    bottom: 0px;
    border-top: 2px solid #ccc;
}

BODY.codisto-categories-index #anchor-content #page\:main-container .admin__old
{
	width: 100%;
    height: 100%;
}

BODY.codisto-categories-index #anchor-content #page\:main-container .admin__old #container.main-col
{
    width: 100%;
    height: 100%;
    border-top: 2px solid black;
}

BODY.codisto-categories-index #anchor-content #page\:main-container .admin__old #container.main-col IFRAME
{
	border: none;
    width: 100%;
    height: 100%;
    padding-right: 88px;
}

BODY.codisto-categories-index .page-footer
{
	display: none;
}

</style>

<iframe src="/admin/codisto/ebaytab/categories"></iframe>