<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:500,900,700,400">

<iframe id="dummy-data" frameborder="0" src="https://codisto.com/xpressgriddemo/ebayedit/"></iframe>
<div id="dummy-data-overlay"></div>
<div id="create-account-modal">
    <h1>Codisto LINQ - Account Creation</h1>
    <form method="post">
        <input type="hidden" name="action" value="codisto_create"/>
        <input type="hidden" name="form_key" value="<?php echo $form_key ?>"/>

        <div class="option active" style="display: none;">
            <label>
                <input type="radio" name="method" value="ebay">
                <div style="display: inline-block;">
                    <img style="height: 20px;" src="https://d31wxntiwn0x96.cloudfront.net/connect/29137/ebaytab/images/ebay.png" scale="0">
                    <div style="padding-top: 6px;">Link your eBay account to create an account automatically</div>
                </div>
            </label>
        </div>

    <div class="or" style="display: none;">
        <strong>OR</strong>
    </div>

    <div class="option">
        <label>
            <input type="radio" name="method" value="email" checked="checked" style="display: none;">
            <div style="display: inline-block;">
                <input type="text" name="email" value="<?php echo htmlspecialchars($email) ?>" size="40">
                <div style="padding-top: 10px;">Register with your email address</div>
            </div>
        </label>
    </div>

    <div class="selection">
        Default Store Country:<br/>
        <div class="select-html-wrapper"></div>
        <br/>
        This is important for creating your initial store defaults.
    </div>

    <div class="next">
        <button class="button button-primary">Next</button>
    </div>

    </form>
    <div class="footer">
    Once you create an account we will begin synchronizing your catalog data.<br>
    Sit tight, this may take several minutes depending on the size of your catalog.<br>
    When completed, you'll have the world's best eBay integration at your fingertips.<br><br/>
    You'll be able to:
    <ul>
        <li>Sync in real-time between Magento &amp; Amazon &amp; eBay</li>
        <li>have Codisto auto-categorize your products into eBay categories</li>
        <li>Access our sophisticated template engine for amazing listings</li>
        <li>and lots more…</li>
    </ul>
    </div>
</div>
